### ISSUE TITLE
Aporte

### ISSUE THREAD

**Issue by AzulPetrocelli** [pdepjuevesTT/2024-presentacion-FVancevic#1]
La presentación la borraría ya que no habla de vos sino de Mariel, como para que quede mas lindo las listas podrías ponerle * al principio y al final para que el texto te quede en itálica, por cierto gracias a tu presentación descubrí porque no podía cargar la imagen a la mía, así que gracias.

**Comment by FVancevic** [comment]
Joya, ahí cambio esas cosas. Por que era que no podías cargar la imagen en tu presentación?

**Comment by AzulPetrocelli** [comment]
supongo que era por el tipo de imagen xq el resto lo había hecho igual, vi que la que subiste vs era png y la que yo quería subir era jpg, así que la descargue como png y sirvió.

**Comment by FVancevic** [comment]
Ah bueno bien, tuve suerte entonces porque de casualidad la mía era png
