### ISSUE TITLE
Sugerencia para agregar a información adicional.

### ISSUE THREAD

**Issue by Kuentas** [pdepjuevesTT/2024-presentacion-FVancevic#2]
Hola Felipe, te quería sugerir si podías agregar un poco mas de información acerca de tu cursada anterior de esta materia, por ejemplo que te gustó mas de lo que cursaste, qué te fue mas complicado hasta ese momento, etc.

**Comment by FVancevic** [comment]
Dale, ahi agrego esa información.

**Comment by Kuentas** [comment]
Genial, muchas gracias!!

**Comment by FVancevic** [comment]
Buenísimo, de nada.
